version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies"
      - python -m pip install --upgrade pip
      - pip install -r requirements.txt
      - mkdir -p artifact/.ebextensions

  pre_build:
    commands:
      - echo "Running tests"

  build:
    commands:
      - pytest -v
      - echo "Packaging artifact"
      - cp -r app artifact/
      - cp application.py artifact/
      - cp requirements.txt artifact/
      - cp -r .ebextensions artifact/

  post_build:
    commands:
      - echo "Build finished"

artifacts:
  base-directory: artifact
  files:
    - '**/*'